server:
  port: 7777
spring:
  cloud:
    nacos:
      discovery:    #nacos注册中心相关配置
        server-addr: 192.168.247.134:8848
        username: naocs
        password: nacos

#jwt超时时间以及sercet配置
jwt:
  expire: 600000
  secrect: hahhahahahahhahaaheheheheheheheheyhehyheyhehy