version: "3"
services:
  nacos-server:
    image: nacos/nacos-server
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    restart:
      always
    volumes:
      - /opt/nacos/standalone-logs/:/home/nacos/logs
      - ./custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8847:8848"
  mysql-server:
    image: mysql:5.6
    environment:
      - MYSQL-ROOT-PASSWORD=1234
    restart:
      always
    volumes:
      - /opt/mysql-server/data:/var/lib/mysql
      - ./cloud_his.sql:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
  redis-server:
    image: redis:latest
    ports:
      - "6379:6379"