server:
  port: 18080
spring:
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss   #表单数据日期字符串与date对象转换规则
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  #json数据的日期格式转换规则
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:    #nacos注册中心相关配置
        server-addr: 192.168.247.134:8848
        username: naocs
        password: nacos
  redis:   # 缓存数据库redis的配置
    host: 192.168.247.134
    port: 6379
  datasource: #数据库连接池的配置
    url: jdbc:mysql://192.168.247.134:3306/cloud-his?useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234567
mybatis: # xml所存放的位置，因此需要在resources目录下创建子目录mappers
  mapper-locations: classpath:/mappers/*.xml
pagehelper: # 设置分页插件的方言用mysql
  auto-dialect: mysql  # 配置分页插件的方言

#jwt超时时间以及sercet配置
jwt:
  expire: 600000
  secrect: hahhahahahahhahaaheheheheheheheheyhehyheyhehy